name: CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Empty JSON File
      run: |
        echo '{}' > ml_ops_risque_climatique/data/logs/results_query.json

    - name: Run Tests
      run: |
        python -m pytest

