name: CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update config.json
        run: echo "`jq '.sampleArray[0].id="5"' config.json`" > config.json
    - name: read config.json
        run: cat config.json



